# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'securerandom'
require 'dotenv'

default_platform(:android)



mobile_ci_alerts = "https://hooks.slack.com/services/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"
dev_build_slack_channel = ""
dev_release_slack_channel = ""

specific_emoji = "SPECIFIC_EMOJI"
      #TODO app name
app_name = "APP_NAME"

pipeline_name = "PIPELINE_NAME"


pipelines_map = {
  "android-app-rc" => {
    "emoji" => ":android:",
    "app_name" => "New App"
  }
}

platform :android do

  desc "set artifact path"
    lane :check_execution do
       s3_bucket_object_url = "s3://pipeline-artifacts-davo-101/tf-cicd/tf-code/}"
       date = "\"2023-07-18 11:13:29\""
       key = "'KEY'"
       sh("aws s3 ls --recursive '#{s3_bucket_object_url}' | awk '$1 < #{date} {print $4}' | xargs -n1 -t -I '#{key}' aws s3 rm '#{s3_bucket_object_url}#{key}'")
       puts "Running test lane"
    end


end



desc "Common setup for all lanes"
before_all do |lane, options|
      properties = Dotenv.load('../fastlane.properties')
      puts "reading ci.properties"
      testingEnabled = properties['fastlane_testing_enable']
      if testingEnabled == 'true'
         puts "changing channel to mobile ci alert"
         dev_build_slack_channel = mobile_ci_alerts
         dev_release_slack_channel = mobile_ci_alerts
         deployment_track = "alpha"
      end

      puts "Printing pipeline_name"
      puts pipeline_name
      if app_name == 'APP_NAME'
        puts "inside renaming block"
        specific_emoji = pipelines_map[pipeline_name]["emoji"]
        app_name       = pipelines_map[pipeline_name]["app_name"]
      end

      puts "channel name printing"
      puts mobile_ci_alerts

      puts "Printing app name"
      puts app_name
      puts specific_emoji
#
#    slack(message: "#{specific_emoji} #{app_name} \n\n check_execution is initiated for the #{app_name} code.",
#                   slack_url: mobile_ci_alerts,
#                   default_payloads: [:git_branch, :git_author]
#     )
end

desc "Common setup for all lanes"
after_all do |lane, options|
#   slack(message: "#{specific_emoji} #{app_name} \n\n check_execution is successfully completed for the #{app_name} code.",
#                 slack_url: mobile_ci_alerts,
#                 default_payloads: [:git_branch, :git_author]
#   )
end
