# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'securerandom'
require 'dotenv'

default_platform(:android)



mobile_ci_alerts = "https://hooks.slack.com/services/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"


pipeline_name = "PIPELINE_NAME"


pipelines_map = {
  "android-app-rc" => {
    "emoji" => ":android:",
    "app_name" => "New App"
  }
}

platform :android do

  desc "set artifact path"
    private_lane :check_execution do
        puts "Running test lane"
  end


end



desc "Common setup for all lanes"
before_all do |lane, options|
      properties = Dotenv.load('../fastlane.properties')
      puts "reading ci.properties"
      testingEnabled = properties['fastlane_testing_enable']
      if testingEnabled == 'true'
         puts "changing channel to mobile ci alert"
         dev_build_slack_channel = mobile_ci_alerts
         dev_release_slack_channel = mobile_ci_alerts
         deployment_track = "alpha"

      end

      if pipeline_name != "PIPELINE_NAME"
        specific_emoji = pipelines_map[pipeline_name]["emoji"]
        app_name       = pipelines_map[pipeline_name]["app_name"]
      end

   lane_detail_text = lane_names_map[:"#{lane}"]
   slack(message: "#{specific_emoji} #{app_name} \n\n #{lane_detail_text} is initiated for the #{app_name} code.",
                  slack_url: mobile_ci_alerts,
                  default_payloads: [:git_branch, :git_author]
    )
end

desc "Common setup for all lanes"
after_all do |lane, options|
  lane_detail_text = lane_names_map[:"#{lane}"]
  slack(message: "#{specific_emoji} #{app_name} \n\n #{lane_detail_text} is successfully completed for the #{app_name} code.",
                slack_url: mobile_ci_alerts,
                default_payloads: [:git_branch, :git_author]
  )
end
